const myImg2 = "https://www.shutterstock.com/shutterstock/photos/2284126663/display_1500/stock-photo-data-science-and-big-data-technology-scientist-computing-analysing-and-visualizing-complex-data-2284126663.jpg"
const myImg = "logo.png"
const myImg3="Student.jpg"
const myImg4="Entrepreneur.webp"
const myImg5="Software.avif"
const myImg6="Market.webp"
const myImg7="Future.webp"
const myImg8="Enthusiast.jpg"
const myImg9="aramco.jpg"
const myImg10="airtel.jpg"
const myImg11="CrowdStrike.webp"
const myImg12="Dell.webp"
export {myImg2, myImg, myImg3, myImg4, myImg5, myImg6, myImg7, myImg8, myImg9, myImg10, myImg11, myImg12}